### ISSUE TITLE
setting? to choose which checksum to validate with

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/wasapi-downloader#92]
In WasapiDownloader, we are validating downloaded files with the MD5 checksum, but it should be a configurable option -- MD5 or SHA1 at this point ...

**Comment by ndushay** [comment]
actually, the option should match the case, etc from WASAPI, currently `md5` and `sha1`

**Comment by ndushay** [comment]
Set this in settings.properties:
- [x] add sample setting in config/settings.properties with clear comment #107
- [x] add command line arg??? #107
- [ ] add info to README
- [x] add to shared_config  settings.properties sul-dlss/shared_configs#292

**Comment by ndushay** [comment]
in branch add-settings;  not doing PR yet (waiting for #102 to be merged first)
